### ISSUE TITLE
Document what each command does at the JIRA level

### ISSUE THREAD

**Issue by jlebon** [coreos/rhcosbot#5]
It'd be nice if there was documentation walking through what each command does at the JIRA level. E.g. status transitions, keywords added, cross-links made, etc... The idea is that if the bot goes down, a human could keep doing what the bot would do, and once the bot is back up, it wouldn't be confused and could pick up from where the human left off.

**Comment by bgilbert** [comment]
PR in #7.  Following Fred Brooks, I've opted to show my tables and leave my flowcharts implicit.

**Comment by miabbott** [comment]
> PR in #7. Following Fred Brooks, I've opted to show my tables and leave my flowcharts implicit.

I had to look up this reference, so just sharing for anyone following along - https://libquotes.com/fred-brooks/quote/lbe4p3u
